#!/bin/bash

gcloud kms encrypt \
    --ciphertext-file=$1.enc \
    --plaintext-file=$1 \
    --project=mbarna-kubernetes-clusters \
    --keyring=dataform-builder-keyring \
    --key=dataform-builder-key \
    --location=global
